project_id = "udvevmetftkcfqwdknjj"

[functions.seed-demo]
verify_jwt = false

[functions.admin-users]
verify_jwt = true

[functions.send-checklist-email]
verify_jwt = true

[functions.seed-team]
verify_jwt = false

[functions.send-driver-checkout]
verify_jwt = true

